Fix PHP error thrown with using importer in PHP7
When importing a file with the zip importer using PHP7:

TypeError: SimpleXMLElement::__construct() expects parameter 1 to be
string, array given in SimpleXMLElement->__construct().

JIRA Issue: ISLANDORA-1906